# Generated by Django 3.1.1 on 2020-09-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornan', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='age',
        ),
    ]
